server:
  port: 8080
  # Add HTTPS support configuration
  ssl:
    enabled: false  # Set to true if you want to enable HTTPS directly in Spring Boot
  # Add CORS configuration at server level
  servlet:
    context-path: /

spring:
  application:
    name: traefik-config-manager

# Traefik Configuration Properties
traefik:
  config:
    dokploy-api-key: "DokployAPIfiIorjkXByApJeEEeXIrCkxtMntiEbLFBdBwypmBzSiIhuUuQlALRdTuEBxSYRDt"
    api-domain: "https://dp.imvj.in"
    application-id: "mp7_3lbuC06Ok3VXbGF0n"
    backend-service: "devcrm-crmbackend-service"
    frontend-service: "devcrm-crmfrontend-service"
    # For single service configurations, you can use:
    # single-service: "your-single-service-name"
    # single-service-port: 8080
    # skip-middlewares: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    disable-swagger-default-url: true
    filter: true
  show-actuator: false

logging:
  level:
    com.traefikconfig: INFO
    com.traefikconfig.service.impl: INFO
    com.traefikconfig.controller: INFO
    org.springframework.web: WARN
    org.springframework.boot: WARN
    root: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %cyan([%15.15t]) %yellow(%-40.40logger{39}) : %msg%n"